### ISSUE TITLE
Some of syntactically incorrect submissions can be compiled successfully

### ISSUE THREAD

**Issue by lv2020** [pmorvalho/C-Pack-IPAs#1]
Thanks for the contribution of a new dataset for C language! I just downloaded the dataset and found that about 60 programs could be compiled successfully with "gcc -std=c90 -ansi -pedantic", like syntactically_incorrect_submissions/year-2/lab03/ex06/ex06-stu_049-sub_015.c. May I confirm how you compile the programs? My gcc version is 11.2. Thanks.

**Comment by pmorvalho** [comment]
Hi,

We are currently using the following compilation flags:

gcc -Wall -Wextra -Werror -ansi -pedantic -lm ex06.c

The flag -Werror generates a compilation error regarding variable i, which is an unused variable.

Thanks for the question. I'm going to add the compilation flags to the README.
